// Angular/Configuring your Chart/Update Attribute/app.component.ts
import { Component } from '@angular/core';

import * as FusionCharts from 'fusioncharts';

// We are importing data and schema from an external source
import DataJson from '../../assets/data.json';
import SchemaJson from '../../assets/schema.json';

@Component({
  selector: 'app-update-attribute',
  templateUrl: './update-attribute.component.html',
  styles: []
})
export class AppComponent {
  dataSource: any;
  type: string;
  width: string;
  height: string;

  constructor() {
    this.type = 'timeseries';
    this.width = '800';
    this.height = '600';
    // We are first creating a DataStore using the data and schema we just imported
    // After that we used it to create a DataTable
    const dataTable = new FusionCharts.DataStore().createDataTable(
      DataJson,
      SchemaJson
    );

    // This is the initial dataSource for our chart
    this.dataSource = {
      data: dataTable,
      caption: {
        text: 'Temperature & Humidity at Emerald City and Gotham City'
      },
      subcaption: {
        text: 'Over the last 28 years'
      },
      series: 'Place',
      yAxis: [
        {
          plot: 'Temperature',
          title: 'Temperature(°C)',
          format: {
            suffix: '°C'
          },
          referenceline: [
            {
              label: 'Controlled Temperature',
              value: '20'
            }
          ]
        },
        {
          plot: 'Humidity',
          title: 'Humidity(%)',
          format: {
            suffix: '%'
          }
        }
      ]
    };
  }

  updateAttr() {
    // Just add or update the attribute in the dataSource and it will get reflected in the chart.
    this.dataSource.yAxis[0].referenceline[0].style = {
      marker: {
        fill: '#41f459',
        stroke: '#41f459'
      }
    };
  }
}

<fusioncharts
  [type]="type"
  [height]="height"
  [width]="width"
  [dataSource]="dataSource"
></fusioncharts>
<button class="btn" (click)="updateAttr()">
  Update Reference Line Color
</button>

// React/Configuring your Chart/Update Attribute/App.js
// Time Series Attribute Update example
import React, { Component } from 'react';
import FusionCharts from 'fusioncharts';
import TimeSeries from 'fusioncharts/fusioncharts.timeseries';
import ReactFC from 'react-fusioncharts';

ReactFC.fcRoot(FusionCharts, TimeSeries);

const jsonify = res => res.json();

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      timeseriesDs: {
        type: 'timeseries',
        width: '800',
        height: '600',
        dataSource: {
          data: null,
          caption: {
            text: 'Temperature & Humidity at Emerald City and Gotham City'
          },
          subcaption: {
            text: 'Over the last 28 years'
          },
          series: 'Place',
          yAxis: [
            {
              plot: 'Temperature',
              title: 'Temperature(°C)',
              format: {
                suffix: '°C'
              },
              referenceline: [
                {
                  label: 'Controlled Temperature',
                  value: '20'
                }
              ]
            },
            {
              plot: 'Humidity',
              title: 'Humidity(%)',
              format: {
                suffix: '%'
              }
            }
          ]
        }
      }
    };
    this.updateAttribute = this.updateAttribute.bind(this);
  }

  // We are creating our DataStore immediately after a component is mounted
  componentDidMount() {
    this.createDataTable();
  }

  createDataTable() {
    const dataFetch = fetch('data.json').then(jsonify);
    const schemaFetch = fetch('schema.json').then(jsonify);
    Promise.all([dataFetch, schemaFetch]).then(res => {
      const data = res[0];
      const schema = res[1];
      // Here we are creating our DataTable
      const dataTable = new FusionCharts.DataStore().createDataTable(
        data,
        schema
      );
      const timeseriesDs = Object.assign({}, this.state.timeseriesDs);
      timeseriesDs.dataSource.data = dataTable;
      this.setState({
        timeseriesDs
      });
    });
  }

  updateAttribute() {
    const timeseriesDs = Object.assign({}, this.state.timeseriesDs);
    // Just add or update the attribute in the dataSource and it will get reflected in the chart.
    timeseriesDs.dataSource.yAxis[0].referenceline[0].style = {
      marker: {
        fill: '#41f459',
        stroke: '#41f459'
      }
    };
    this.setState({
      timeseriesDs
    });
  }

  render() {
    return (
      <div>
        <ReactFC {...this.state.timeseriesDs} />
        <button className="btn" onClick={this.updateAttribute}>
          Update Reference Line Color
        </button>
      </div>
    );
  }
}

export default App;
