// React/Configuring your Chart/Update Data/App.js
// Time Series Data Update example
import React, { Component } from 'react';
import FusionCharts from 'fusioncharts';
import TimeSeries from '../Update Attribute/node_modules/fusioncharts/fusioncharts.timeseries';
import ReactFC from '../Update Attribute/node_modules/react-fusioncharts';

ReactFC.fcRoot(FusionCharts, TimeSeries);

const jsonify = res => res.json();
const dataFetch = fetch(
  'https://s3.eu-central-1.amazonaws.com/fusion.store/ft/data/line-chart-with-time-axis-data.json'
).then(jsonify);
const schemaFetch = fetch(
  'https://s3.eu-central-1.amazonaws.com/fusion.store/ft/schema/line-chart-with-time-axis-schema.json'
).then(jsonify);

class App extends Component {
  constructor(props) {
    super(props);
    // In this method we are fetching our data and schema from remote URLs and creating our DataTable
    this.state = {
      timeseriesDs: {
        type: 'timeseries',
        width: '800',
        height: '600',
        dataSource: {
          caption: { text: 'Online Sales of a SuperStore in the US' },
          data: null,
          yAxis: [
            {
              plot: [
                {
                  value: 'Sales ($)'
                }
              ]
            }
          ]
        }
      }
    };
    this.updateData = this.updateData.bind(this);
  }
  // We are creating our DataStore immediately after a component is mounted
  componentDidMount() {
    this.onFetchData();
  }
  onFetchData() {
    Promise.all([dataFetch, schemaFetch]).then(res => {
      const data = res[0];
      const schema = res[1];
      // Here we are creating our DataTable
      const dataTable = new FusionCharts.DataStore().createDataTable(
        data,
        schema
      );
      const timeseriesDs = Object.assign({}, this.state.timeseriesDs);
      timeseriesDs.dataSource.data = dataTable;
      this.setState({
        timeseriesDs
      });
    });
  }

  updateData() {
    // You can create DataTables multiple times using different data and schema.
    const dataFetch = fetch('data.json').then(jsonify);
    const schemaFetch = fetch('schema.json').then(jsonify);
    Promise.all([dataFetch, schemaFetch]).then(res => {
      const data = res[0];
      const schema = res[1];
      const dataTable = new FusionCharts.DataStore().createDataTable(
        data,
        schema
      );
      const timeseriesDs = Object.assign({}, this.state.timeseriesDs);
      timeseriesDs.dataSource.caption.text =
        'Temperature & Humidity at Emerald City and Gotham City';
      timeseriesDs.dataSource.series = 'Place';
      timeseriesDs.dataSource.yAxis = [
        {
          plot: 'Temperature',
          title: 'Temperature(°C)',
          format: {
            suffix: '°C'
          }
        },
        {
          plot: 'Humidity',
          title: 'Humidity(%)',
          format: {
            suffix: '%'
          }
        }
      ];

      // Then you can update the data in your dataSource with the newly created dataTable
      // and it will get reflected in the chart.
      timeseriesDs.dataSource.data = dataTable;
      this.setState({
        timeseriesDs
      });
    });
  }

  render() {
    return (
      <div>
        <ReactFC {...this.state.timeseriesDs} />
        <button className="btn" onClick={this.updateData}>
          Update Data
        </button>
      </div>
    );
  }
}

export default App;

// Angular/Configuring your Chart/Update Data/app.component.ts
import { Component } from '@angular/core';

import * as FusionCharts from 'fusioncharts';

// We are importing data and schema from an external source
import DataJson from '../../assets/data.json';
import SchemaJson from '../../assets/schema.json';

const jsonify = res => res.json();
const dataFetch = fetch(
  'https://s3.eu-central-1.amazonaws.com/fusion.store/ft/data/line-chart-with-time-axis-data.json'
).then(jsonify);
const schemaFetch = fetch(
  'https://s3.eu-central-1.amazonaws.com/fusion.store/ft/schema/line-chart-with-time-axis-schema.json'
).then(jsonify);

@Component({
  selector: 'app-update-data',
  templateUrl: './update-data.component.html',
  styles: ['update-data.component.css']
})
export class UpdateDataComponent {
  dataSource: any;
  type: string;
  width: string;
  height: string;
  constructor() {
    this.type = 'timeseries';
    this.width = '800';
    this.height = '600';
    // This is the initial dataSource for our chart
    this.dataSource = {
      caption: { text: 'Online Sales of a SuperStore in the US' },
      data: null,
      yAxis: [
        {
          plot: [
            {
              value: 'Sales ($)'
            }
          ]
        }
      ]
    };
    this.fetchData();
  }

  fetchData() {
    Promise.all([dataFetch, schemaFetch]).then(res => {
      const data = res[0];
      const schema = res[1];
      // Here we are creating our DataTable for the first time
      const dataTable = new FusionCharts.DataStore().createDataTable(
        data,
        schema
      );
      this.dataSource.data = dataTable;
    });
  }

  updateData() {
    // You can create DataTables multiple times using different data and schema.
    const dataTable = new FusionCharts.DataStore().createDataTable(
      DataJson,
      SchemaJson
    );
    // Then you can update the data in your dataSource with the newly created dataTable
    // and it will get reflected in the chart.
    this.dataSource = {
      data: dataTable,
      caption: {
        text: 'Temperature & Humidity at Emerald City and Gotham City'
      },
      subcaption: {
        text: 'Over the last 28 years'
      },
      series: 'Place',
      yAxis: [
        {
          plot: 'Temperature',
          title: 'Temperature(°C)',
          format: {
            suffix: '°C'
          }
        },
        {
          plot: 'Humidity',
          title: 'Humidity(%)',
          format: {
            suffix: '%'
          }
        }
      ]
    };
  }
}

<fusioncharts
  [type]="type"
  [height]="height"
  [width]="width"
  [dataSource]="dataSource"
></fusioncharts>
<button class="btn" (click)="updateData()">Update Data</button>
